// Code generated by "stringer -type=viewStateEnum"; DO NOT EDIT.

package tui

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[mainTimerPage-0]
	_ = x[addTimerPage-1]
}

const _viewStateEnum_name = "mainTimerPageaddTimerPage"

var _viewStateEnum_index = [...]uint8{0, 13, 25}

func (i viewStateEnum) String() string {
	if i < 0 || i >= viewStateEnum(len(_viewStateEnum_index)-1) {
		return "viewStateEnum(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _viewStateEnum_name[_viewStateEnum_index[i]:_viewStateEnum_index[i+1]]
}
