// Code generated by "stringer -type=TimerStateEnum"; DO NOT EDIT.

package timerdata

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TimerStateRunning-0]
	_ = x[TimerStatePaused-1]
	_ = x[TimerStateRinging-2]
	_ = x[TimerStateFinished-3]
}

const _TimerStateEnum_name = "TimerStateRunningTimerStatePausedTimerStateRingingTimerStateFinished"

var _TimerStateEnum_index = [...]uint8{0, 17, 33, 50, 68}

func (i TimerStateEnum) String() string {
	if i < 0 || i >= TimerStateEnum(len(_TimerStateEnum_index)-1) {
		return "TimerStateEnum(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TimerStateEnum_name[_TimerStateEnum_index[i]:_TimerStateEnum_index[i+1]]
}
